cargo_cache:
  folder: $CARGO_HOME/registry
  fingerprint_script: cat Cargo.lock || echo ""

task:
  env:
    HOME: /tmp # cargo cache needs it
  freebsd_instance:
    image: freebsd-12-4-release-amd64
  matrix:
    - name: FreeBSD stable
      env:
        VERSION: 1.65.0
    - name: FreeBSD nightly
      env:
        VERSION: nightly
  setup_script:
    - pkg install -y fusefs-libs pkgconf
    - kldload fusefs
    - fetch https://sh.rustup.rs -o rustup.sh
    - sh rustup.sh -y
    - $HOME/.cargo/bin/rustup toolchain install $VERSION
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION build
  test_script:
    - . $HOME/.cargo/env
    - cargo +$VERSION test
  clippy_script:
    - . $HOME/.cargo/env
    - if [ "$VERSION" = "nightly" ]; then cargo +$VERSION clippy --all-targets -- -D warnings; else true; fi
  audit_script:
    - . $HOME/.cargo/env
    - if [ "$VERSION" = "nightly" ]; then
    -   pkg install -y cargo-audit
    -   cargo audit
    - fi
  before_cache_script: rm -rf $HOME/.cargo/registry/index
