[package]
name = "xfs-fuse"
description = "Read-only FUSE server implementing XFS"
version = "0.1.0"
edition = "2018"
authors = ["Khaled Emara <mail@khaledemara.dev>"]
repository = "https://github.com/KhaledEmaraDev/xfuse"
categories = ["filesystem"]
exclude = [
  "/.gitignore",
  "/.cirrus.yml"
]

[dependencies]
fuse = "0.3.1"
byteorder = "1.4.3"
libc = "0.2.97"
time = "0.1.44"
uuid = "0.8.2"
num-traits = "0.2.14"
num-derive = "0.3.3"

[dependencies.clap]
version = "2"
default-features = false
features=  [ "suggestions", "color", "wrap_help" ]
