.Dd August 26, 2021
.Dt XFUSE 1
.Os
.Sh NAME
.Nm xfs-fuse
.Nd Mount an XFS filesystem
.Sh SYNOPSIS
.Nm
.Op Ar device
.Op Ar mountpoint
.Sh DESCRIPTION
.Nm
can be used to attach an XFS filesystem found on
.Ar device
to
.Ar mountpoint
in the unix filesystem tree.
.Pp
The options are as follows:
.Bl -tag -width indent
.It Ar device
The device that carries the XFS filesystem data.
.It Ar mountpoint
The path in the current unix filesystem tree to attach
.Ar device
to.
.El
.Pp
.El
.Sh EXIT STATUS
.Ex -std
