.Dd July 15, 2025
.Dt XFUSE 1
.Os
.Sh NAME
.Nm xfs-fuse
.Nd Mount an XFS filesystem
.Sh SYNOPSIS
.Nm
.Op Fl fhV
.Op Fl o Ar options
.Ar device
.Ar mountpoint
.Sh DESCRIPTION
.Nm
can be used to mount an XFS filesystem found on
.Ar device
to
.Ar mountpoint .
.Pp
The options are as follows:
.Bl -tag -width indent
.It Fl f
Run in the foreground instead of daemonizing.
.It Fl o
Pass various common options to the kernel.
See
.Xr mount_fusefs 8
for the list.
.It Fl h , -help
Print usage information and exit.
.It Fl V , -version
Print the version and exit.
.El
.Pp
.El
.Sh EXIT STATUS
.Ex -std
