pub const XFS_SB_MAGIC: u32 = 0x58465342; // Superblock
pub const XFS_AGF_MAGIC: u32 = 0x58414746; // Free Space
pub const XFS_AGI_MAGIC: u32 = 0x58414749; // Inode Information
pub const XFS_DINODE_MAGIC: u16 = 0x494e; // Inodes
pub const XFS_DQUOT_MAGIC: u16 = 0x4451; // Quota Inodes
pub const XFS_SYMLINK_MAGIC: u32 = 0x58534c4d; // Symbolic Links
pub const XFS_ABTB_MAGIC: u32 = 0x41425442; // Free Space by Block B+tree
pub const XFS_ABTC_MAGIC: u32 = 0x41425443; // Free Space by Size B+tree
pub const XFS_IBT_MAGIC: u32 = 0x49414254; // Inode B+tree
pub const XFS_FIBT_MAGIC: u32 = 0x46494254; // Free Inode B+tree
pub const XFS_BMAP_MAGIC: u32 = 0x424d4150; // B+Tree Extent List
pub const XLOG_HEADER_MAGIC_NUM: u32 = 0xfeedbabe; // Log Records
pub const XFS_DA_NODE_MAGIC: u16 = 0xfebe; // Directory/Attribute Node
pub const XFS_DIR2_BLOCK_MAGIC: u32 = 0x58443242; // Block Directory Data
pub const XFS_DIR2_DATA_MAGIC: u32 = 0x58443244; // Leaf Directory Data
pub const XFS_DIR2_LEAF1_MAGIC: u16 = 0xd2f1; // Leaf Directory
pub const XFS_DIR2_LEAFN_MAGIC: u16 = 0xd2ff; // Node Directory
pub const XFS_DIR2_FREE_MAGIC: u32 = 0x58443246; // Node Directory Free Space
pub const XFS_ATTR_LEAF_MAGIC: u16 = 0xfbee; // Leaf Attribute
pub const XFS_MD_MAGIC: u32 = 0x5846534d; // Metadata Dumps

pub type XfsIno = u64; // absolute inode number
pub type XfsOff = i64; // file offset
pub type XfsDaddr = i64; // disk address (sectors)
pub type XfsAgnumber = u32; // AG number
pub type XfsAgblock = u32; // AG relative block number
pub type XfsExtlen = u32; // extent length in blocks
pub type XfsExtnum = i32; // number of extends in a data fork
pub type XfsAextnum = i16; // number of extents in an attribute fork
pub type XfsDablk = u32; // block number for directories and extended attributes
pub type XfsDahash = u32; // hash of a directory file name or extended attribute name
pub type XfsFsblock = u64; // filesystem block number combining AG number
pub type XfsRfsblock = u64; // raw filesystem block number
pub type XfsRtblock = u64; // extent number in the real-time sub-volume
pub type XfsFileoff = u64; // block offset into a file
pub type XfsFilblks = u64; // block count for a file
pub type Uuid = [u8; 16]; // 16-byte universally unique identifier (UUID).
pub type XfsFsize = i64; // byte size of a file
